name: My First GitHub Action

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Say Hello
      run: echo "Hello, World! This is GitHub Actions."

    - name: Run a basic command
      run: |
        echo "Listing files in repository:"
        ls -la
